server:
  host: "0.0.0.0"
  port: "8000"
  timeout: 15


jetstream:
  addresses: 
  - "0.0.0.0:4222"
  topic_prefix: "Yuta"

metrics:
  enabled: true

tracing:
  enabled: false

logging:
  - type: "stdout"
    level: "DEBUG"


chatClients:
  - username: "yuta"
    password: "verystronkpassword"
    homeserverurl: "dendrite.maibaloc.com"
    type: "matrix"

nluClients:
  - projectid: "yuta-seig"
    languagecode: "en-US"
    type: "diaglogflow"
